{
"class" : "AssetPrototype",
"classname" : "MagicFlowerFairytale",
"title" : "Цветок сказки",
"description" : "Убирай любой мусор в гостях у друзей или же у себя дома, на даче или в мире, чтобы получить Семечку Сказки. Можно купить в магазине в разделе \"Особенные\" - \"Ресурсы\".",
"tags" : ["seed_simple","category_2"],
"group" : "seeds",
"subgroup" : "magic",
"price" : 1,
"currency" : "money",
"sell_price" : 3,
"meta_info" : "life=1800;states=3;spoil_period=10800",
"energy_cost" : "energy=1",
"accelerate_cost" : "asset=AccelerationPlantBooster:1",
"recover_cost" : "asset=RecoverPlantBooster:1",
"register_event_counter_on_buy" : 1,
"shop_conditions" : "active_quest_group=MagicFlowerFairytale",
"extra" : {"hide_in_shop" : 1},
"rand_reward" : {"all":[{"p":50, "asset":"MagicShieldFairytale"}],
                 "xp":50},
"rand_reward_in_guest" : {"reputation_progress":1,
                          "xp":5},
"id" : 25456
}