{
"class" : "AssetPrototype",
"classname" : "VegetableSeedAsparagus",
"title" : "Семена спаржи",
"description" : "Спаржа",
"tags" : ["seed_vegetable","seed_simple","category_2"],
"group" : "seeds",
"subgroup" : "vegetables",
"price" : 1,
"currency" : "money",
"sell_price" : 3,
"meta_info" : "life=300;states=3;spoil_period=14400;icon_view_seed=1;help_view=VegetableSeedAsparagusHelpIcon;location_board_view=VegetableAsparagus;pack_asset=VegetableSeedAsparagus_Package",
"rand_reward" : {"asset":"VegetableAsparagus", "xp":4},
"rand_reward_in_guest" : {"reputation_progress":1, "xp":4},
"energy_cost" : "dexterity=1",
"accelerate_cost" : "asset=AccelerationPlantBooster:1",
"recover_cost" : "asset=RecoverPlantBooster:1",
"shop_conditions" : "done_quest=FarmNew2_Pack1_Balcony1",
"id" : 32454
}