{
"class" : "AssetPrototype",
"classname" : "VegetableSeedCucumber",
"title" : "Семена огурца",
"description" : "Огурец",
"tags" : ["seed_vegetable","seed_simple","category_2"],
"group" : "seeds",
"subgroup" : "vegetables",
"price" : 1,
"currency" : "money",
"sell_price" : 3,
"meta_info" : "life=7200;states=3;icon_view_seed=1;spoil_period=14400;help_view=VegetableSeedCucumberHelpIcon;location_board_view=VegetableCucumber;pack_asset=VegetableSeedCucumber_Package",
"rand_reward" : {"asset":"VegetableCucumber", "xp":16},
"rand_reward_in_guest" : {"reputation_progress":1, "xp":3},
"energy_cost" : "dexterity=1",
"accelerate_cost" : "asset=AccelerationPlantBooster:1",
"recover_cost" : "asset=RecoverPlantBooster:1",
"shop_conditions" : "done_quest=FarmNewfoundCottager11",
"id" : 7779
}