{
"class" : "AssetPrototype",
"classname" : "VegetableSeedPepper",
"title" : "Семена перца",
"description" : "Перец",
"tags" : ["seed_vegetable","seed_simple","category_2"],
"group" : "seeds",
"subgroup" : "vegetables",
"price" : 1,
"currency" : "money",
"sell_price" : 3,
"meta_info" : "life=21600;states=3;icon_view_seed=1;spoil_period=28800;help_view=VegetableSeedPepperHelpIcon;location_board_view=VegetablePepper;pack_asset=VegetableSeedPepper_Package",
"rand_reward" : {"asset":"VegetablePepper", "xp":22},
"rand_reward_in_guest" : {"reputation_progress":1, "xp":5},
"energy_cost" : "dexterity=1",
"accelerate_cost" : "asset=AccelerationPlantBooster:1",
"recover_cost" : "asset=RecoverPlantBooster:1",
"shop_conditions" : "done_quest=FarmBaleenStriped10",
"id" : 7775
}