{
"class" : "AssetPrototype",
"classname" : "VegetableSeedEggplant",
"title" : "Семена баклажана",
"description" : "Баклажан",
"tags" : ["seed_vegetable","seed_simple","category_2"],
"group" : "seeds",
"subgroup" : "vegetables",
"price" : 1,
"currency" : "money",
"sell_price" : 3,
"meta_info" : "life=14400;states=3;icon_view_seed=1;spoil_period=21600;help_view=VegetableSeedEggplantHelpIcon;location_board_view=VegetableEggplant;pack_asset=VegetableSeedEggplant_Package",
"rand_reward" : {"asset":"VegetableEggplant", "xp":20},
"rand_reward_in_guest" : {"reputation_progress":1, "xp":5},
"energy_cost" : "dexterity=1",
"accelerate_cost" : "asset=AccelerationPlantBooster:1",
"recover_cost" : "asset=RecoverPlantBooster:1",
"shop_conditions" : "done_quest=FarmNewfoundCottager11",
"id" : 7781
}