{
"class" : "AssetPrototype",
"classname" : "VegetableSeedPotato",
"title" : "Семена картофеля",
"description" : "Картофель",
"tags" : ["seed_vegetable","seed_simple","category_3"],
"group" : "seeds",
"subgroup" : "vegetables",
"price" : 1,
"currency" : "money",
"sell_price" : 3,
"meta_info" : "life=28800;states=3;icon_view_seed=1;help_view=VegetableSeedPotatoHelpIcon;location_board_view=VegetablePotato;pack_asset=VegetableSeedPotato_Package",
"rand_reward" : {"asset":"VegetablePotato", "xp":24},
"rand_reward_in_guest" : {"reputation_progress":1, "xp":5},
"energy_cost" : "dexterity=1",
"accelerate_cost" : "asset=AccelerationPlantBooster:1",
"recover_cost" : "asset=RecoverPlantBooster:1",
"shop_conditions" : "done_quest=FarmBaleenStriped10",
"id" : 7776
}