{
"class" : "AssetPrototype",
"classname" : "BeetlePaws",
"title" : "Жучок кверху лапками",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "190681804",
"rand_reward" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"WebMillCollection1",
					"p":20},
				{"asset":"WebMillCollection2",
					"p":100},
				{"asset":"WebMillCollection3",
					"p":100},
				{"asset":"WebMillCollection4",
					"p":100},
				{"asset":"WebMillCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"WebMillCollection1",
					"p":20},
				{"asset":"WebMillCollection2",
					"p":100},
				{"asset":"WebMillCollection3",
					"p":100},
				{"asset":"WebMillCollection4",
					"p":100},
				{"asset":"WebMillCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}