{
"class" : "AssetPrototype",
"classname" : "BittingPie",
"title" : "Надкусанный пирожок",
"group" : "garbage",
"subgroup" : "on_the_floor",
"action_availability_conditions" : "done_quest=home1_clean_personage",
"description" : "Сначала помыться надо, а потом мусор убирать.",
"g_pest_probability_percent" : "16",
"id" : "140162016",
"rand_reward" : {"all":
		[{"p":66,
			"one_of":
		[{"asset":"CocoonMillCollection1",
					"p":25},
				{"asset":"CocoonMillCollection2",
					"p":100},
				{"asset":"CocoonMillCollection3",
					"p":100},
				{"asset":"CocoonMillCollection4",
					"p":100},
				{"asset":"CocoonMillCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"CocoonMillCollection1",
					"p":25},
				{"asset":"CocoonMillCollection2",
					"p":100},
				{"asset":"CocoonMillCollection3",
					"p":100},
				{"asset":"CocoonMillCollection4",
					"p":100},
				{"asset":"CocoonMillCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}