{
"class" : "AssetPrototype",
"classname" : "BrokenPipe",
"title" : "Сломанная дудка",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "50134045",
"rand_reward" : {"all":
		[{"p":66,
			"one_of":
		[{"asset":"CocoonHorseWithTelegaCollection1",
					"p":100},
				{"asset":"CocoonHorseWithTelegaCollection2",
					"p":100},
				{"asset":"CocoonHorseWithTelegaCollection3",
					"p":30},
				{"asset":"CocoonHorseWithTelegaCollection4",
					"p":100},
				{"asset":"CocoonHorseWithTelegaCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"CocoonHorseWithTelegaCollection1",
					"p":100},
				{"asset":"CocoonHorseWithTelegaCollection2",
					"p":100},
				{"asset":"CocoonHorseWithTelegaCollection3",
					"p":25},
				{"asset":"CocoonHorseWithTelegaCollection4",
					"p":100},
				{"asset":"CocoonHorseWithTelegaCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}