{
"class" : "AssetPrototype",
"classname" : "BrokenPlate",
"title" : "Разбитая тарелка",
"group" : "garbage",
"subgroup" : "on_the_floor",
"action_availability_conditions" : "done_quest=home1_clean_personage",
"description" : "Сначала помыться надо, а потом мусор убирать.",
"g_pest_probability_percent" : "15",
"id" : "76295666",
"rand_reward" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"CocoonPottersWheelCollection1",
					"p":100},
				{"asset":"CocoonPottersWheelCollection2",
					"p":100},
				{"asset":"CocoonPottersWheelCollection3",
					"p":20},
				{"asset":"CocoonPottersWheelCollection4",
					"p":100},
				{"asset":"CocoonPottersWheelCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"CocoonPottersWheelCollection1",
					"p":100},
				{"asset":"CocoonPottersWheelCollection2",
					"p":100},
				{"asset":"CocoonPottersWheelCollection3",
					"p":20},
				{"asset":"CocoonPottersWheelCollection4",
					"p":100},
				{"asset":"CocoonPottersWheelCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}