{
"class" : "AssetPrototype",
"classname" : "BrokenBasketForNeedlework",
"title" : "Сломанная корзиночка для рукоделия",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "267347379",
"rand_reward" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"CocoonDistaffCollection1",
					"p":20},
				{"asset":"CocoonDistaffCollection2",
					"p":100},
				{"asset":"CocoonDistaffCollection3",
					"p":100},
				{"asset":"CocoonDistaffCollection4",
					"p":100},
				{"asset":"CocoonDistaffCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"CocoonDistaffCollection1",
					"p":20},
				{"asset":"CocoonDistaffCollection2",
					"p":100},
				{"asset":"CocoonDistaffCollection3",
					"p":100},
				{"asset":"CocoonDistaffCollection4",
					"p":100},
				{"asset":"CocoonDistaffCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}