{
"class" : "AssetPrototype",
"classname" : "CandyWrapper",
"title" : "Фантик",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "111899124",
"rand_reward" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"CandyWrapperCollection1",
					"p":100},
				{"asset":"CandyWrapperCollection2",
					"p":100},
				{"asset":"CandyWrapperCollection3",
					"p":100},
				{"asset":"CandyWrapperCollection4",
					"p":50},
				{"asset":"CandyWrapperCollection5",
					"p":20}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"CandyWrapperCollection1",
					"p":100},
				{"asset":"CandyWrapperCollection2",
					"p":100},
				{"asset":"CandyWrapperCollection3",
					"p":100},
				{"asset":"CandyWrapperCollection4",
					"p":50},
				{"asset":"CandyWrapperCollection5",
					"p":15}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}