{
"class" : "AssetPrototype",
"classname" : "ChickenFeathers",
"title" : "Куриные перышки",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : 2564,
"rand_reward" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"ChickenFeathersCollection1",
					"p":100},
				{"asset":"ChickenFeathersCollection2",
					"p":85},
				{"asset":"ChickenFeathersCollection3",
					"p":100},
				{"asset":"ChickenFeathersCollection4",
					"p":7},
				{"asset":"ChickenFeathersCollection5",
					"p":70}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"ChickenFeathersCollection1",
					"p":100},
				{"asset":"ChickenFeathersCollection2",
					"p":85},
				{"asset":"ChickenFeathersCollection3",
					"p":100},
				{"asset":"ChickenFeathersCollection4",
					"p":7},
				{"asset":"ChickenFeathersCollection5",
					"p":70}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}