{
"class" : "AssetPrototype",
"classname" : "CircassianWalnutShell",
"title" : "Скорлупки грецкого ореха",
"group" : "garbage",
"subgroup" : "on_the_floor",
"price" : "1",
"currency" : "money_alt",
"g_pest_probability_percent" : "16",
"id" : "180803722",
"rand_reward" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"CircassianWalnutShellCollection1",
					"p":100},
				{"asset":"CircassianWalnutShellCollection2",
					"p":100},
				{"asset":"CircassianWalnutShellCollection3",
					"p":100},
				{"asset":"CircassianWalnutShellCollection4",
					"p":50},
				{"asset":"CircassianWalnutShellCollection5",
					"p":50}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"CircassianWalnutShellCollection1",
					"p":100},
				{"asset":"CircassianWalnutShellCollection2",
					"p":100},
				{"asset":"CircassianWalnutShellCollection3",
					"p":100},
				{"asset":"CircassianWalnutShellCollection4",
					"p":50},
				{"asset":"CircassianWalnutShellCollection5",
					"p":50}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}