{
"class" : "AssetPrototype",
"classname" : "DirtyTowel",
"title" : "Грязное полотенце",
"group" : "garbage",
"subgroup" : "on_the_floor",
"action_availability_conditions" : "done_quest=home1_clean_personage",
"description" : "Сначала помыться надо, а потом мусор убирать.",
"g_pest_probability_percent" : "16",
"id" : 261379724,
"rand_reward" : {"all":[{"p":66,"one_of":[{"asset":"CocoonStoveCollection1", "p":36},
                                          {"asset":"CocoonStoveCollection2", "p":100},
                                          {"asset":"CocoonStoveCollection3", "p":50},
                                          {"asset":"CocoonStoveCollection4", "p":50},
                                          {"asset":"CocoonStoveCollection5", "p":30}]},
                       {"p":5,"energy":1}],
                 "money_alt":1,
                 "xp":1},
"rand_reward_in_guest" : {"all":[{"p":33,"one_of":[{"asset":"CocoonStoveCollection1","p":36},
                                                   {"asset":"CocoonStoveCollection2","p":100},
                                                   {"asset":"CocoonStoveCollection3","p":50},
                                                   {"asset":"CocoonStoveCollection4","p":50},
                                                   {"asset":"CocoonStoveCollection5","p":30}]},
                                 {"p":5,"energy":1}],
                          "money_alt":1,
                          "reputation_progress":1,
                          "xp":1}
}