{
"class" : "AssetPrototype",
"classname" : "DirtyPan",
"title" : "Грязная сковорода",
"group" : "garbage",
"subgroup" : "on_the_floor",
"action_availability_conditions" : "done_quest=home1_clean_personage",
"description" : "Сначала помыться надо, а потом мусор убирать.",
"g_pest_probability_percent" : "16",
"id" : "110100472",
"rand_reward" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"WebStoveCollection1",
					"p":5},
				{"asset":"WebStoveCollection2",
					"p":100},
				{"asset":"WebStoveCollection3",
					"p":100},
				{"asset":"WebStoveCollection4",
					"p":100},
				{"asset":"WebStoveCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"WebStoveCollection1",
					"p":5},
				{"asset":"WebStoveCollection2",
					"p":100},
				{"asset":"WebStoveCollection3",
					"p":100},
				{"asset":"WebStoveCollection4",
					"p":100},
				{"asset":"WebStoveCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}