{
"class" : "AssetPrototype",
"classname" : "EmptySpoolOfThread",
"title" : "Пустая катушка для ниток",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "199578312",
"rand_reward" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"WebTambourCollection1",
					"p":100},
				{"asset":"WebTambourCollection2",
					"p":100},
				{"asset":"WebTambourCollection3",
					"p":100},
				{"asset":"WebTambourCollection4",
					"p":100},
				{"asset":"WebTambourCollection5",
					"p":20}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"WebTambourCollection1",
					"p":100},
				{"asset":"WebTambourCollection2",
					"p":100},
				{"asset":"WebTambourCollection3",
					"p":100},
				{"asset":"WebTambourCollection4",
					"p":100},
				{"asset":"WebTambourCollection5",
					"p":20}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}