{
"class" : "AssetPrototype",
"classname" : "FlapOfTissue",
"title" : "Лоскут ткани",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "38613359",
"rand_reward" : {"all":
		[{"p":66,
			"one_of":
		[{"asset":"CocoonTambourCollection1",
					"p":100},
				{"asset":"CocoonTambourCollection2",
					"p":100},
				{"asset":"CocoonTambourCollection3",
					"p":10},
				{"asset":"CocoonTambourCollection4",
					"p":100},
				{"asset":"CocoonTambourCollection5",
					"p":50}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"CocoonTambourCollection1",
					"p":100},
				{"asset":"CocoonTambourCollection2",
					"p":100},
				{"asset":"CocoonTambourCollection3",
					"p":10},
				{"asset":"CocoonTambourCollection4",
					"p":100},
				{"asset":"CocoonTambourCollection5",
					"p":50}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}