{
"class" : "AssetPrototype",
"classname" : "FoxTrail",
"title" : "След от лисьей лапки",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : 2563,
"rand_reward" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"FoxTrailCollection1",
					"p":100},
				{"asset":"FoxTrailCollection2",
					"p":100},
				{"asset":"FoxTrailCollection3",
					"p":100},
				{"asset":"FoxTrailCollection4",
					"p":100},
				{"asset":"FoxTrailCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"FoxTrailCollection1",
					"p":100},
				{"asset":"FoxTrailCollection2",
					"p":100},
				{"asset":"FoxTrailCollection3",
					"p":100},
				{"asset":"FoxTrailCollection4",
					"p":100},
				{"asset":"FoxTrailCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}