{
"class" : "AssetPrototype",
"classname" : "FrameBroken",
"title" : "Фоторамка разбитая",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_collection_assets_ru" : "WebDistaffCollection1:100|WebDistaffCollection2:100|WebDistaffCollection3:20|WebDistaffCollection4:100|WebDistaffCollection5:100",
"g_collection_assets_studivz" : "WebDistaffCollection1:100|WebDistaffCollection2:100|WebDistaffCollection3:20|WebDistaffCollection4:100|WebDistaffCollection5:100",
"g_pest_probability_percent" : "16",
"id" : "86453366",
"rand_reward" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"WebDistaffCollection1",
					"p":100},
				{"asset":"WebDistaffCollection2",
					"p":100},
				{"asset":"WebDistaffCollection3",
					"p":40},
				{"asset":"WebDistaffCollection4",
					"p":100},
				{"asset":"WebDistaffCollection5",
					"p":100}]},
		{"p":5, "energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":40,
			"one_of":
		[{"asset":"WebDistaffCollection1",
					"p":100},
				{"asset":"WebDistaffCollection2",
					"p":100},
				{"asset":"WebDistaffCollection3",
					"p":14},
				{"asset":"WebDistaffCollection4",
					"p":100},
				{"asset":"WebDistaffCollection5",
					"p":100}]},
		{"p":5, "energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}