{
"class" : "AssetPrototype",
"classname" : "HandfulGrain",
"title" : "Горстка зерна",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : 2565,
"rand_reward" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"HandfulGrainCollection1",
					"p":80},
				{"asset":"HandfulGrainCollection2",
					"p":10},
				{"asset":"HandfulGrainCollection3",
					"p":90},
				{"asset":"HandfulGrainCollection4",
					"p":80},
				{"asset":"HandfulGrainCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"HandfulGrainCollection1",
					"p":80},
				{"asset":"HandfulGrainCollection2",
					"p":10},
				{"asset":"HandfulGrainCollection3",
					"p":90},
				{"asset":"HandfulGrainCollection4",
					"p":80},
				{"asset":"HandfulGrainCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}