{
"class" : "AssetPrototype",
"classname" : "LeakyShoe",
"title" : "Дырявая калоша",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "230938865",
"rand_reward" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"WebAnvilCollection1",
					"p":100},
				{"asset":"WebAnvilCollection2",
					"p":100},
				{"asset":"WebAnvilCollection3",
					"p":50},
				{"asset":"WebAnvilCollection4",
					"p":100},
				{"asset":"WebAnvilCollection5",
					"p":20}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"WebAnvilCollection1",
					"p":100},
				{"asset":"WebAnvilCollection2",
					"p":100},
				{"asset":"WebAnvilCollection3",
					"p":50},
				{"asset":"WebAnvilCollection4",
					"p":100},
				{"asset":"WebAnvilCollection5",
					"p":20}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}