{
"class" : "AssetPrototype",
"classname" : "LeakyBucket",
"title" : "Дырявое ведро",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "42230861",
"rand_reward" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"WebHorseWithTelegaCollection1",
					"p":100},
				{"asset":"WebHorseWithTelegaCollection2",
					"p":100},
				{"asset":"WebHorseWithTelegaCollection3",
					"p":100},
				{"asset":"WebHorseWithTelegaCollection4",
					"p":100},
				{"asset":"WebHorseWithTelegaCollection5",
					"p":100}]}],
	"money_alt":2,
	"xp":3},
"rand_reward_in_guest" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"WebHorseWithTelegaCollection1",
					"p":100},
				{"asset":"WebHorseWithTelegaCollection2",
					"p":100},
				{"asset":"WebHorseWithTelegaCollection3",
					"p":100},
				{"asset":"WebHorseWithTelegaCollection4",
					"p":100},
				{"asset":"WebHorseWithTelegaCollection5",
					"p":100}]}],
	"money_alt":2,
	"reputation_progress":1,
	"xp":3}
}