{
"class" : "AssetPrototype",
"classname" : "SaltShakerWithSpilledSalt",
"title" : "Солонка",
"group" : "garbage",
"subgroup" : "on_the_floor",
"action_availability_conditions" : "done_quest=home1_clean_personage",
"description" : "Сначала помыться надо, а потом мусор убирать.",
"g_pest_probability_percent" : "16",
"id" : "225888513",
"rand_reward" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"WebBarrelForPicklesCollection1",
					"p":100},
				{"asset":"WebBarrelForPicklesCollection2",
					"p":100},
				{"asset":"WebBarrelForPicklesCollection3",
					"p":100},
				{"asset":"WebBarrelForPicklesCollection4",
					"p":20},
				{"asset":"WebBarrelForPicklesCollection5",
					"p":50}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"WebBarrelForPicklesCollection1",
					"p":100},
				{"asset":"WebBarrelForPicklesCollection2",
					"p":100},
				{"asset":"WebBarrelForPicklesCollection3",
					"p":100},
				{"asset":"WebBarrelForPicklesCollection4",
					"p":15},
				{"asset":"WebBarrelForPicklesCollection5",
					"p":50}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}