{
"class" : "AssetPrototype",
"classname" : "SamovarBoot",
"title" : "Сапог от самовара ",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "94012664",
"rand_reward" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"SamovarBootCollection1",
					"p":30},
				{"asset":"SamovarBootCollection2",
					"p":100},
				{"asset":"SamovarBootCollection3",
					"p":100},
				{"asset":"SamovarBootCollection4",
					"p":100},
				{"asset":"SamovarBootCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"SamovarBootCollection1",
					"p":30},
				{"asset":"SamovarBootCollection2",
					"p":100},
				{"asset":"SamovarBootCollection3",
					"p":100},
				{"asset":"SamovarBootCollection4",
					"p":100},
				{"asset":"SamovarBootCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}