{
"class" : "AssetPrototype",
"classname" : "SmashedEarthenwarePot",
"title" : "Разбитая крынка",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : "248709585",
"rand_reward" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"WebPottersWheelCollection1",
					"p":100},
				{"asset":"WebPottersWheelCollection2",
					"p":100},
				{"asset":"WebPottersWheelCollection3",
					"p":100},
				{"asset":"WebPottersWheelCollection4",
					"p":50},
				{"asset":"WebPottersWheelCollection5",
					"p":10}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":40,
			"one_of":
		[{"asset":"WebPottersWheelCollection1",
					"p":100},
				{"asset":"WebPottersWheelCollection2",
					"p":100},
				{"asset":"WebPottersWheelCollection3",
					"p":100},
				{"asset":"WebPottersWheelCollection4",
					"p":50},
				{"asset":"WebPottersWheelCollection5",
					"p":5}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}