{
"class" : "AssetPrototype",
"classname" : "WebAnvil",
"title" : "Паутина на наковальне",
"group" : "garbage",
"subgroup" : "on_asset",
"tags":["exclude_for_generation"],
"id" : "239056061",
"rand_reward" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"DeadLeafCollection1",
					"p":50},
				{"asset":"DeadLeafCollection2",
					"p":100},
				{"asset":"DeadLeafCollection3",
					"p":100},
				{"asset":"DeadLeafCollection4",
					"p":100},
				{"asset":"DeadLeafCollection5",
					"p":50}]}],
	"money_alt":2,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":50,
			"one_of":
		[{"asset":"DeadLeafCollection1",
					"p":50},
				{"asset":"DeadLeafCollection2",
					"p":100},
				{"asset":"DeadLeafCollection3",
					"p":100},
				{"asset":"DeadLeafCollection4",
					"p":100},
				{"asset":"DeadLeafCollection5",
					"p":50}]}],
	"money_alt":2,
	"reputation_progress":1,
	"xp":1}
}