{
"class" : "AssetPrototype",
"classname" : "WebCommon",
"title" : "Паутина",
"group" : "garbage",
"subgroup" : "on_the_wall",
"tags":["idle"],
"action_availability_conditions" : "done_quest=home1_clean_personage",
"description" : "Сначала помыться надо, а потом мусор убирать.",
"g_pest_probability_percent" : "16",
"id" : "60795854",
"rand_reward" : {"all":
		[{"p":40,
			"one_of":
		[{"asset":"WebCommonCollection1",
					"p":50},
				{"asset":"WebCommonCollection2",
					"p":20},
				{"asset":"WebCommonCollection3",
					"p":100},
				{"asset":"WebCommonCollection4",
					"p":100},
				{"asset":"WebCommonCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"WebCommonCollection1",
					"p":50},
				{"asset":"WebCommonCollection2",
					"p":14},
				{"asset":"WebCommonCollection3",
					"p":100},
				{"asset":"WebCommonCollection4",
					"p":100},
				{"asset":"WebCommonCollection5",
					"p":100}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}