{
"class" : "AssetPrototype",
"classname" : "WebDistaff",
"title" : "Паутина на прялке",
"group" : "garbage",
"subgroup" : "on_asset",
"tags":["exclude_for_generation"],
"id" : "131114049",
"rand_reward" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"MirrorFragmentCollection1",
					"p":100},
				{"asset":"MirrorFragmentCollection2",
					"p":100},
				{"asset":"MirrorFragmentCollection3",
					"p":100},
				{"asset":"MirrorFragmentCollection4",
					"p":100},
				{"asset":"MirrorFragmentCollection5",
					"p":100}]}],
	"money_alt":2,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"MirrorFragmentCollection1",
					"p":100},
				{"asset":"MirrorFragmentCollection2",
					"p":100},
				{"asset":"MirrorFragmentCollection3",
					"p":100},
				{"asset":"MirrorFragmentCollection4",
					"p":100},
				{"asset":"MirrorFragmentCollection5",
					"p":100}]}],
	"money_alt":2,
	"reputation_progress":1,
	"xp":1}
}