{
"class" : "AssetPrototype",
"classname" : "WebTambour",
"title" : "Паутина на пяльцах",
"group" : "garbage",
"subgroup" : "on_asset",
"tags":["exclude_for_generation"],
"id" : "131405557",
"rand_reward" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"YarnLumpcCollection1",
					"p":100},
				{"asset":"YarnLumpcCollection2",
					"p":100},
				{"asset":"YarnLumpcCollection3",
					"p":100},
				{"asset":"YarnLumpcCollection4",
					"p":100},
				{"asset":"YarnLumpcCollection5",
					"p":100}]}],
	"money_alt":2,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":75,
			"one_of":
		[{"asset":"YarnLumpcCollection1",
					"p":100},
				{"asset":"YarnLumpcCollection2",
					"p":100},
				{"asset":"YarnLumpcCollection3",
					"p":100},
				{"asset":"YarnLumpcCollection4",
					"p":100},
				{"asset":"YarnLumpcCollection5",
					"p":100}]}],
	"money_alt":2,
	"reputation_progress":1,
	"xp":1}
}