{
"class" : "AssetPrototype",
"classname" : "WickerBasket",
"title" : "Дно корзинки",
"group" : "garbage",
"subgroup" : "on_the_floor",
"g_pest_probability_percent" : "16",
"id" : 2586,
"rand_reward" : {"all":
		[{"p":55,
			"one_of":
		[{"asset":"WickerBasketCollection1",
					"p":100},
				{"asset":"WickerBasketCollection2",
					"p":100},
				{"asset":"WickerBasketCollection3",
					"p":5},
				{"asset":"WickerBasketCollection4",
					"p":89},
				{"asset":"WickerBasketCollection5",
					"p":5}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"xp":1},
"rand_reward_in_guest" : {"all":
		[{"p":33,
			"one_of":
		[{"asset":"WickerBasketCollection1",
					"p":100},
				{"asset":"WickerBasketCollection2",
					"p":100},
				{"asset":"WickerBasketCollection3",
					"p":5},
				{"asset":"WickerBasketCollection4",
					"p":89},
				{"asset":"WickerBasketCollection5",
					"p":5}]},
		{"p":5,
			"energy":1}],
	"money_alt":1,
	"reputation_progress":1,
	"xp":1}
}